In [1]:
import sys
sys.path.append('../')

import torch
from torch import nn
from torch.utils.data import DataLoader
from torchvision import datasets, transforms

from architectures.AlexNet import *

import matplotlib.pyplot as plt 

In [2]:
%matplotlib inline
%load_ext autoreload
%autoreload 2

In [3]:
# parameters
RANDOM_SEED = 42
LEARNING_RATE = 0.001
BATCH_SIZE = 32
N_EPOCHS = 1

IMG_SIZE = 32
N_CLASSES = 1000

In [4]:
# define transforms
transform = transforms.Compose([
    transforms.Resize(256), 
    transforms.CenterCrop(224),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]), # mean activity over the training set from the paper
])

# Dataset

In [5]:
# download and create datasets
train_dataset = datasets.ImageNet(root='./imagenet_data', 
                               split='train', 
                               transform=transforms,
                               download=True)

valid_dataset = datasets.ImageNet(root='./imagenet_data', 
                               split='val', 
                               transform=transforms)

RuntimeError: The dataset is no longer publicly accessible. You need to download the archives externally and place them in the root directory.

In [75]:
avg = nn.AvgPool2d(kernel_size = 2, stride=1)

In [79]:
x = torch.tensor([
    [
        [1, 1, 1, 1],
        [2, 2, 2, 2],
        [3, 3, 3, 3],
        [4, 4, 4, 4]
    ],
    [
        [10, 10, 10, 10],
        [20, 20, 20, 20],
        [30, 30, 30, 30],
        [40, 40, 40, 40]
    ]
], dtype=float).view((1,2,4,4))

In [80]:
x.shape

torch.Size([1, 2, 4, 4])

In [81]:
avg(x)

tensor([[[[ 1.5000,  1.5000,  1.5000],
          [ 2.5000,  2.5000,  2.5000],
          [ 3.5000,  3.5000,  3.5000]],

         [[15.0000, 15.0000, 15.0000],
          [25.0000, 25.0000, 25.0000],
          [35.0000, 35.0000, 35.0000]]]], dtype=torch.float64)

In [84]:
(x**2).unsqueeze(1).shape

torch.Size([1, 1, 2, 4, 4])

In [90]:
layer = LocalResponceNorm(n=2,across_channels=True)
layer(x)

tensor([[[[ 0.5935,  0.5935,  0.5935,  0.5935],
          [ 1.1803,  1.1803,  1.1803,  1.1803],
          [ 1.7540,  1.7540,  1.7540,  1.7540],
          [ 2.3088,  2.3088,  2.3088,  2.3088]],

         [[ 5.9348,  5.9348,  5.9348,  5.9348],
          [11.8028, 11.8028, 11.8028, 11.8028],
          [17.5400, 17.5400, 17.5400, 17.5400],
          [23.0880, 23.0880, 23.0880, 23.0880]]]], dtype=torch.float64)

In [109]:
layer = LocalResponceNorm(n=5,across_channels=False)
layer(x)

tensor([[[[ 0.5946,  0.5946,  0.5946,  0.5946],
          [ 1.1890,  1.1890,  1.1890,  1.1890],
          [ 1.7836,  1.7835,  1.7835,  1.7836],
          [ 2.3781,  2.3780,  2.3780,  2.3781]],

         [[ 5.9088,  5.8966,  5.8966,  5.9088],
          [11.7340, 11.6824, 11.6824, 11.7340],
          [17.6010, 17.5236, 17.5236, 17.6010],
          [23.4784, 23.3785, 23.3785, 23.4784]]]], dtype=torch.float64)

In [110]:
nn.LocalResponseNorm(5, k=2, alpha=1e-04, beta=0.75)(x)

tensor([[[[ 0.5942,  0.5942,  0.5942,  0.5942],
          [ 1.1856,  1.1856,  1.1856,  1.1856],
          [ 1.7717,  1.7717,  1.7717,  1.7717],
          [ 2.3500,  2.3500,  2.3500,  2.3500]],

         [[ 5.9415,  5.9415,  5.9415,  5.9415],
          [11.8562, 11.8562, 11.8562, 11.8562],
          [17.7175, 17.7175, 17.7175, 17.7175],
          [23.4999, 23.4999, 23.4999, 23.4999]]]], dtype=torch.float64)